### ISSUE TITLE
[NEW] Consider a setting to force all keys to be volatile with a default/max TTL

### ISSUE THREAD

**Issue by mikethea1** [madolson/placeholderkv#1739]
Apologies in advance if this feature already exists or there is a better existing solution and I just didn't find it. I'm relatively new to Valkey!

**The problem/use-case that the feature addresses**

I have a Valkey cluster that I use purely as a cache. Therefore, I want every key to be created with some TTL so that we can avoid "leaks" where we're storing (and paying for) more data than we need to.

Today, this relies on developer vigilance. It's particularly tricky because many commands that create keys don't provide the option to set an expiration at the same time. In my understanding then if we wanted to do this and _guarantee_ the expiration we'd need a transaction or a Lua script, which feels cumbersome and easy for someone to forget.

**Description of the feature**

It would be nice to have a configuration setting where you can set the default and perhaps the max expiry for keys. With this setting enabled, keys that would normally be created as non-volatile would instead be created as volatile with the default expiry. If max expiry is supported, then any command which sets the expiry could be capped to the max value.

**Alternatives you've considered**

As mentioned previously, currently we're solving this by manually setting expirations and trying to route most developer usage through common utility functions that handle this correctly. We can also leverage the volatile/nonvolatile key count metrics we get from AWS to identify if we messed something up after the fact.

I also found the [maxmemory](https://valkey.io/topics/lru-cache/) feature. This feels like a good solution to the worst-case scenario of a massive leak, but it seems like would take a very long time to catch a slow leak especially since the cache size is always changing with variation in usage and as new features are added that leverage the cache.

Finally, it seems like I could rig up a Lua script to scan all the keys regularly and expire any that are non-volatile. This would work but seems like it could be expensive/slow.

**Comment by zuiderkwast** [comment]
We don't have a `default-ttl` feature. Maybe we can add it but let's first see if it's really necessary.

It sounds to me that `maxmemory allkeys-lru` would be good for your use case.

Why do you say leak? If the keys are still valid and recently used, it's better to keep them as long as there is enough memory, isn't it? I don't understand why you want to guarantee expiration.

Are you worried that some keys are evicted too early? You say you use it purely as a cache so this shouldn't be a problem. Am I missing something?

Disclaimer: I don't know AWS price model. Do you pay for storage per second or somerging like that?

**Comment by mikethea1** [comment]
Thanks for responding @zuiderkwast. 

> Disclaimer: I don't know AWS price model. Do you pay for storage per second or somerging like that?

Exactly. One of the charges is data storage in GB hours. See the "serverless" section on [this page](https://aws.amazon.com/elasticache/pricing/).

> Why do you say leak? If the keys are still valid and recently used, it's better to keep them as long as there is enough memory, isn't it? I don't understand why you want to guarantee expiration.

Since I get charged for storage, I would consider "abandoned" cache keys to be leaks. I'd get charged for them forever even though the key has outlived its use in terms of relevance to the application (the chance of a cache hit is either zero or vanishingly small).

> It sounds to me that maxmemory allkeys-lru would be good for your use case.

My understanding is that `maxmemory` applies at the node level rather than the cluster level, and that serverless elasticache will attempt to autoscale the cluster before maxmemory is reached, so the only time the maxmemory will come into effect is if a sudden load spike overwhelmed the autoscaler.

Even if there were a way to apply a maxmemory setting at the cluster level, that wouldn't really fit my use-case. I'd be happy to have the cluster autoscale up (at least to a point) if that is driven by increased load from the application. I just don't want to one developer mixup to result in steady, unnecessary cache growth that we get charged for despite it not adding value.

Does that make sense?

**Comment by zuiderkwast** [comment]
> > Do you pay for storage per second or somerging like that?
> 
> Exactly. One of the charges is data storage in GB hours.

In that case, this makes sense. The maxmemory based eviction was designed for computers where the available memory is fixed.

> My understanding is that `maxmemory` applies at the node level rather than the cluster level,

That's right. It's not trivial to use in a cluster.

> and that serverless elasticache will attempt to autoscale the cluster before maxmemory is reached, so the only time the maxmemory will come into effect is if a sudden load spike overwhelmed the autoscaler.

If this is true, it doesn't sound great. It effectively makes LRU eviction impossible to use in the serverless offering. I would ask their support about this.

> Even if there were a way to apply a maxmemory setting at the cluster level, that wouldn't really fit my use-case.

I get it. Yes, this makes sense to me.

**Comment by mikethea1** [comment]
Thanks for adding to the roadmap ideas list!

> If this is true, it doesn't sound great. It effectively makes LRU eviction impossible to use in the serverless offering. I would ask their support about this.

Based on [these docs](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Scaling.html), it looks like they let you set a full-cluster memory limit and will engage the `volatile-LRU` policy once that's reached. Some posts I found suggest you can switch over to `allkeys-LRU` through configuration. However, as I said this doesn't really solve the problem since the goal is to have the cache scale up and down based on usage vs. a fixed-size scenario where you might as well max out the capacity you've allocated.

**Comment by madolson** [comment]
@ranshid Didn't you have some idea related to data policy, where you could specify data constraints on parts of the key space? Another option as well could be triggers, where we could add a TTL if it doesn't exist.

**Comment by madolson** [comment]
For reference, this was a request in Redis as well. https://github.com/redis/redis/issues/8323. There is even some recent activity on it.

**Comment by hpatro** [comment]
IIRC SegCache had this notion of a max TTL of around a month for entries without any TTL provided. However, deciding this max TTL by Valkey or providing user to pick a value could be difficult to get it right to avoid mass eviction of keys. 

@mikethea1 as your use case is purely for caching, do you use cache-aside? And for the scenario mentioned above, you could still be potentially charged for storage if you pick a high default/max TTL (let's say a month) as the pricing is calculated via the avg. of hourly storage usage.

**Comment by zuiderkwast** [comment]
@hpatro How would a max-ttl cause mass eviction of keys? If keys are added over time, the will expire over time.

SegCache has some very different semantics compared to us. They always delete the keys *before* they expire, rather than after. All keys are considered volatile.

**Comment by mikethea1** [comment]
> However, deciding this max TTL by Valkey or providing user to pick a value could be difficult to get it right to avoid mass eviction of keys.

@hpatro can you explain what you mean by this? I think that the default and/or max TTL should always be picked by the user (at configuration time), not by the system.

> @mikethea1 as your use case is purely for caching, do you use cache-aside?

Yes that's the pattern we use. In many instances the access patterns mean that we can also use renew-on-access which allows the TTL to be shorter without incurring misses.

> And for the scenario mentioned above, you could still be potentially charged for storage if you pick a high default/max TTL (let's say a month) as the pricing is calculated via the avg. of hourly storage usage.

I understand. Any cache is going to have entries that won't get hit again and yes I'll have to pay for them. What I'm looking to avoid is edge cases where a developer mistake or error during cache population means a keys get created with no TTL at all, at which point I'm paying for it forever until I can locate and clean it up (that's why I use the term "leak," it feels comparable to a memory leak). Default/max TTL allows the system to be self-healing in that regard.

**Comment by hpatro** [comment]
> @hpatro How would a max-ttl cause mass eviction of keys? If keys are added over time, the will expire over time.


I was talking about use cases where folks load the entire dataset at the start of the cache like restoring a RDB.

**Comment by zuiderkwast** [comment]
> I was talking about use cases where folks load the entire dataset at the start of the cache like restoring a RDB.

Good point. The active expiration does some max amount of work per cycle though so it shouldn't cause a latency spike at least. Then I don't see why mass eviction would be a problem.

**Comment by hpatro** [comment]
> [@hpatro](https://github.com/hpatro) can you explain what you mean by this? I think that the default and/or max TTL should always be picked by the user (at configuration time), not by the system.

I was speaking about the idea in SegCache, in that the system picks a default of a high TTL (like a month or so). I guess in Valkey it makes sense for advanced users to pick their own default TTL or keys can still exists without a TTL, which isn't possible in case of SegCache.

**Comment by hpatro** [comment]
> > I was talking about use cases where folks load the entire dataset at the start of the cache like restoring a RDB.
> 
> Good point. The active expiration does some max amount of work per cycle though so it shouldn't cause a latency spike at least. Then I don't see why mass eviction would be a problem.

My thought is mass eviction would cause higher load on the backing database which might not be prepared to handle it.

**Comment by zuiderkwast** [comment]
> My thought is mass eviction would cause higher load on the backing database which might not be prepared to handle it.

Ah, ... not our problem. 🤣 Kidding. Assuming there is a backing database and the keys are is still accessed, I can see that this might become a problem, at least in some scenarios.

If users find this to be a problem, we could add another config to randomize the max-ttl to compensate for this? Let's not solve it before we know we need it?

**Comment by KIvanow** [comment]
Until a default-ttl config lands, the detection half of this is at least workable today, and it might cover the "self-healing" goal more than it first looks.

The thing that helped me with the same leak problem was to stop trying to catch no-TTL keys at write time and instead find them after the fact on a schedule. A full SCAN + TTL pass is slow, which you flagged, but a sampled one is not: pipeline a TTL per key over a few thousand SCANned keys and you get a good estimate of how many no-TTL keys exist and which key prefixes they cluster under. Usually enough to catch a regression the same day rather than months later.
Grouping the no-TTL count by prefix helps too. A single developer mistake tends to show up as one prefix suddenly growing its no-TTL share, which is easier to alert on than a raw total that drifts with normal usage.
None of that enforces a TTL, so it doesn't replace the config you're asking for. But it turns "locate and clean it up eventually" into something you can watch continuously, which sounds close to the leak you're trying to avoid paying for.
