### ISSUE TITLE
[NEW] set performance with io threads is significantly worse when clients use pipelining

### ISSUE THREAD

**Issue by rainsupreme** [madolson/placeholderkv#1753]
**The Problem**

I was benchmarking get/set performance between different release versions and realized that io-threads performance is significantly worse when I test with pipelining=4. It seems that prefetching is not as effective when clients pipeline commands for some reason.

**Desired Improvement**

I think we should investigate why this is the case and improve prefetching with pipelining, since we recommend some amount of pipelining to get the best performance from Valkey.

I've tested three different value sizes now. Each test was run for 1 hour:

testing unstable with io-threads=9:
![Image](https://github.com/user-attachments/assets/5264a4d0-40ab-407d-acd1-075f359d47d3)

testing unstable with 512B data size and io-threads=9:
![Image](https://github.com/user-attachments/assets/d6ff1926-e3eb-459a-bd0d-011619573072)

**Comment by madolson** [comment]
The one exception seems to be in the SADD case, which to me doesn't make a lot of sense to me, but OK.

@uriyage @ranshid  Would you mind reviewing this as well. It looks like Valkey 8.1.Rc1 is better in all cases except the SET with 9 threads case. I'm not aware of any place we would expect a large regression, but maybe we should take a look a look to see if something else was introduced that is consuming CPU.

**Comment by rainsupreme** [comment]
I've rerun the tests, this time throwing out the first 5 minutes of warmup data then running valkey-benchmark over a 1 hour period. Hardware and key size are the same as before. Currently, it looks like GET performance increases with pipelining, but SET performance still suffers from pipelining, though unstable has a smaller penalty than 8.0.

**Comment by rainsupreme** [comment]
I fixed these graphs also after realizing my previous get tests were 0% hit rate

**Comment by Dhruv-Garg79** [comment]
Any update on this issue?
I am using valkey 8.2 running on AWS Elasticache with 2 replica nodes, each of size r7g.large.

And I am seeing quite a lot of `timeouts when using SADD` (Especially when the set doesn't already exist) with pipelined batches of 50 items each; earlier, we were having much larger batch sizes. Reduced due to timeouts, but it's still not better.

Total load on the cluster is around 15K to 20K RPM.

**Comment by rainsupreme** [comment]
@Dhruv-Garg79 Sorry to reply so slowly, but your timeout issue looks to be unrelated. My general advice is to make sure your timeout is fairly generous (on the order of multiple seconds) but that's off topic for this issue. 🙂

**Comment by rainsupreme** [comment]
This issue is resolved. A longitudinal benchmark sweep (10-rep measurements across ~2000 commits on Graviton 3, io-threads=7) pinpoints the regression and fix:

**Regression introduced by:** #763 ("IO thread work offload", Jul 2024)
SET P=10 dropped from 969K to 764K rps while P=1 rose to 839K, making pipelining *actively harmful* (ratio 0.91x).

**Fixed by:** #2092 ("Optimize pipelining by parsing and prefetching multiple commands per IO thread", Aug 2025)
SET P=10 jumped from 977K to 1,416K rps in a single commit, restoring proper pipeline scaling (ratio 1.55x).

**Current state (HEAD, Jul 2026):**

| Workload | RPS | Pipeline scaling |
|----------|-----|-----------------|
| SET P=1 (t7) | 940K | — |
| SET P=10 (t7) | 1,541K | 1.64x |
| SET P=50 (t9) | 1,680K | 1.79x |

Pipelining now consistently improves SET performance across all tested platforms (ARM, AMD, Intel).
